run:
  timeout: 5m
  tests: true

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 4
    min-occurrences: 4
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
    disabled-checks:
      - dupImport
      - ifElseChain
      - octalLiteral
      - whyNoLint
      - wrapperFunc
  gocyclo:
    min-complexity: 20
  goimports:
    local-prefixes: go-jira-helper
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false
  govet:
    shadow: true

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - revive
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-files:
    - ".*\\.pb\\.go$"
  exclude-dirs:
    - vendor

